import type { ReminderCategory } from "@/types/healthTimeline";

import type { HealthOSReminderCategoryConfig } from "./types";

export const HEALTHOS_REMINDER_CATEGORY_CONFIG: Record<
  ReminderCategory,
  HealthOSReminderCategoryConfig
> = {
  appointment: {
    accentColor: "#38bdf8",
    category: "appointment",
    description: "Doctor visits and calendar appointments.",
    label: "Appointments",
    routeTarget: "/health-calendar",
    sensitive: false,
  },
  baby_feeding: {
    accentColor: "#f59e0b",
    category: "baby_feeding",
    description: "Baby feeding prompts.",
    label: "Baby feeding",
    routeTarget: "/baby-child",
    sensitive: true,
  },
  baby_medicine: {
    accentColor: "#fb7185",
    category: "baby_medicine",
    description: "Baby medicine and care reminders.",
    label: "Baby medicine",
    routeTarget: "/baby-child",
    sensitive: true,
  },
  baby_sleep: {
    accentColor: "#a78bfa",
    category: "baby_sleep",
    description: "Baby sleep and nap prompts.",
    label: "Baby sleep",
    routeTarget: "/baby-child",
    sensitive: true,
  },
  biometric_log: {
    accentColor: "#22c55e",
    category: "biometric_log",
    description: "Vitals and health metrics.",
    label: "Biometrics",
    routeTarget: "/biometrics",
    sensitive: true,
  },
  contraception: {
    accentColor: "#f472b6",
    category: "contraception",
    description: "Contraception and cycle-related reminders.",
    label: "Contraception",
    routeTarget: "/cycle",
    sensitive: true,
  },
  custom: {
    accentColor: "#94a3b8",
    category: "custom",
    description: "Custom personal reminders.",
    label: "Custom",
    routeTarget: "/health-calendar",
    sensitive: true,
  },
  family_caregiver: {
    accentColor: "#60a5fa",
    category: "family_caregiver",
    description: "Family and caregiver tasks.",
    label: "Family care",
    routeTarget: "/(tabs)/circle",
    sensitive: true,
  },
  food_meal: {
    accentColor: "#34d399",
    category: "food_meal",
    description: "Meals, nutrition, and grocery prompts.",
    label: "Nutrition",
    routeTarget: "/food",
    sensitive: false,
  },
  lab_follow_up: {
    accentColor: "#818cf8",
    category: "lab_follow_up",
    description: "Lab review and follow-up tasks.",
    label: "Lab follow-up",
    routeTarget: "/records",
    sensitive: true,
  },
  medication: {
    accentColor: "#ef4444",
    category: "medication",
    description: "Medication timing and adherence reminders.",
    label: "Medication",
    routeTarget: "/medication",
    sensitive: true,
  },
  mens_health: {
    accentColor: "#2dd4bf",
    category: "mens_health",
    description: "Men's health check-ins.",
    label: "Men's health",
    routeTarget: "/mens-health",
    sensitive: true,
  },
  pregnancy: {
    accentColor: "#fb7185",
    category: "pregnancy",
    description: "Pregnancy appointments and planning.",
    label: "Pregnancy",
    routeTarget: "/pregnancy",
    sensitive: true,
  },
  prescription_refill: {
    accentColor: "#f97316",
    category: "prescription_refill",
    description: "Prescription refill follow-ups.",
    label: "Refills",
    routeTarget: "/records",
    sensitive: true,
  },
  records: {
    accentColor: "#64748b",
    category: "records",
    description: "Records, documents, and health file follow-ups.",
    label: "Records",
    routeTarget: "/records",
    sensitive: true,
  },
  supplement: {
    accentColor: "#10b981",
    category: "supplement",
    description: "Supplement schedule reminders.",
    label: "Supplements",
    routeTarget: "/supplements",
    sensitive: true,
  },
  vaccine: {
    accentColor: "#06b6d4",
    category: "vaccine",
    description: "Vaccines and immunization follow-ups.",
    label: "Vaccines",
    routeTarget: "/records",
    sensitive: true,
  },
  water: {
    accentColor: "#0ea5e9",
    category: "water",
    description: "Hydration reminders.",
    label: "Water",
    routeTarget: "/food",
    sensitive: false,
  },
  womens_health: {
    accentColor: "#ec4899",
    category: "womens_health",
    description: "Women's health and cycle check-ins.",
    label: "Women's health",
    routeTarget: "/cycle",
    sensitive: true,
  },
  workout: {
    accentColor: "#8b5cf6",
    category: "workout",
    description: "Workout plans and movement reminders.",
    label: "Fitness",
    routeTarget: "/fitness",
    sensitive: false,
  },
};

export function getReminderCategoryConfig(category: ReminderCategory) {
  return HEALTHOS_REMINDER_CATEGORY_CONFIG[category];
}
