import { healthLightTheme, healthRealmAccents } from "./healthTheme";

export const appColors = {
  background: healthLightTheme.background,
  surface: "#ffffff",
  surfaceWarm: healthLightTheme.surfaceSoft,
  surfaceElevated: healthLightTheme.surfaceRaised,
  primary: healthLightTheme.primary,
  primarySoft: healthLightTheme.accent,
  secondary: healthLightTheme.secondaryForeground,
  secondarySoft: healthLightTheme.secondary,
  accent: healthLightTheme.primary,
  accentSoft: healthLightTheme.accent,
  warning: "#a16207",
  warningSoft: "#fef9c3",
  success: "#15803d",
  successSoft: "#dcfce7",
  error: healthLightTheme.destructive,
  errorSoft: "#ffe4e6",
  text: healthLightTheme.foreground,
  textSecondary: healthLightTheme.mutedForeground,
  textMuted: healthLightTheme.mutedForeground,
  border: healthLightTheme.border,
  glassBackground: healthLightTheme.surfaceGlass,
  glassBorder: "rgba(226, 232, 240, 0.8)",
  glassShadow: "rgba(15, 23, 42, 0.08)",
  nav: "#ffffff",
  navActive: "#e2e8f0",
  navInactive: "#64748b",
  navText: "#334155",
  navActiveText: "#0f172a",
  navBorder: "#e2e8f0",
  navShadow: "rgba(15, 23, 42, 0.12)",
  locked: "#475569",
  lockedSoft: "#e2e8f0",
  emergency: "#991b1b",
} as const;

export const realmColors = {
  nutrition: healthRealmAccents.food,
  workout: healthRealmAccents.fitness,
  biometrics: healthRealmAccents.health,
  device_sync: healthRealmAccents.health,
  medication: healthRealmAccents.meds,
  supplements: healthRealmAccents.meds,
  records: healthRealmAccents.records,
  calendar: healthRealmAccents.family,
  womens_health: healthRealmAccents.women,
  pregnancy: healthRealmAccents.women,
  baby_child: healthRealmAccents.baby,
  mens_health: healthRealmAccents.health,
  family: healthRealmAccents.family,
  ai_assistant: healthRealmAccents.health,
} as const;

export const statusColors = {
  success: appColors.success,
  warning: appColors.warning,
  error: appColors.error,
  review: appColors.primary,
  private: appColors.locked,
  shared: appColors.primary,
  locked: appColors.locked,
  neutral: appColors.textMuted,
} as const;
