export type AppModuleKey =
  | "personal_health"
  | "planning"
  | "circle"
  | "child_baby"
  | "pregnancy_cycle"
  | "elder_care"
  | "caregiver"
  | "fitness"
  | "food"
  | "mens_health"
  | "ai_assistant";

export type AppModule = {
  key: AppModuleKey;
  name: string;
  description: string;
  emoji: string;
  core: boolean;
};

export type WidgetKey =
  | "mood"
  | "water"
  | "weight"
  | "biometric_goal_weight"
  | "energy"
  | "resting_heart_rate"
  | "blood_pressure"
  | "blood_glucose"
  | "digestion"
  | "symptoms"
  | "steps_today"
  | "distance_today"
  | "last_synced_workout"
  | "sleep_last_night"
  | "active_calories"
  | "synced_weight"
  | "sync_status"
  | "calories_today"
  | "protein_today"
  | "water_today"
  | "calories_progress"
  | "protein_progress"
  | "water_progress"
  | "fiber_progress"
  | "goal_weight"
  | "nutrition_goal"
  | "food_diary_status"
  | "medication_due_today"
  | "next_medication"
  | "medication_taken_today"
  | "missed_medication"
  | "medication_schedule_status"
  | "supplements_due_today"
  | "next_supplement"
  | "supplements_taken_today"
  | "supplement_schedule_status"
  | "recent_record"
  | "upcoming_follow_up"
  | "prescription_refill"
  | "next_vaccine"
  | "lab_follow_up"
  | "pinned_health_record"
  | "records_needing_attention"
  | "today_reminders"
  | "next_reminder"
  | "overdue_items"
  | "upcoming_appointment"
  | "medication_schedule"
  | "supplement_schedule"
  | "workout_plan"
  | "water_check"
  | "timeline_today"
  | "reminder_next"
  | "reminders_today"
  | "overdue_reminders"
  | "medication_due"
  | "supplement_due"
  | "contraception_next"
  | "baby_reminder"
  | "appointment_reminder"
  | "water_reminder"
  | "workout_reminder"
  | "caregiver_task"
  | "steps"
  | "sleep"
  | "medication"
  | "next_appointment"
  | "work_reminder"
  | "food_log"
  | "workout"
  | "family_status"
  | "caregiver_active"
  | "baby_feed"
  | "next_feed"
  | "last_feed"
  | "sleep_today"
  | "last_sleep"
  | "last_diaper"
  | "weight_latest"
  | "growth_check"
  | "baby_medicine_due"
  | "solid_food_tried"
  | "milestone_check"
  | "baby_note"
  | "baby_today"
  | "cycle"
  | "cycle_private"
  | "cycle_day"
  | "period_expected"
  | "period_active"
  | "fertile_window_estimate"
  | "estimated_ovulation"
  | "symptoms_today"
  | "mood_today"
  | "contraception_reminder"
  | "contraception_status"
  | "contraception_caution"
  | "womens_health_privacy_status"
  | "pregnancy_week"
  | "pregnancy_due_date"
  | "pregnancy_next_appointment"
  | "pregnancy_symptom_log"
  | "pregnancy_medication_review"
  | "pregnancy_question"
  | "pregnancy_record"
  | "pregnancy_privacy_status"
  | "mens_health_check_in"
  | "mens_energy_stress"
  | "testicular_check_reminder"
  | "prostate_discussion_reminder"
  | "fertility_note"
  | "mens_doctor_question"
  | "mens_private_reminder"
  | "mens_health_privacy_status"
  | "elder_checkin"
  | "ai_suggestion";

export type LocalProfileSettings = {
  displayName: string;
  schemaVersion: 1;
  selectedModuleIds: AppModuleKey[];
  updatedAt: string | null;
};

export type ThemeDefinition = {
  colors: {
    background: string;
    border: string;
    card: string;
    mutedText: string;
    primary: string;
    primarySoft: string;
    secondary: string;
    text: string;
    warning: string;
    warningSoft: string;
  };
  radius: {
    button: number;
    card: number;
    pill: number;
  };
  spacing: {
    lg: number;
    md: number;
    sm: number;
    xl: number;
    xs: number;
  };
};
